# Generated by Django 3.1 on 2020-08-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=20)),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('close_price', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('high_price', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('low_price', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('date', models.DateTimeField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
